version: '2'

services:


    jekyll:
        build:
            context: jekyll/docs
        command:
            - jekyll serve --watch --incremental --force_polling
        volumes:
            - ./jekyll/docs:/srv/jekyll
        ports:
            - "4000:4000"

    web:
        image: sosedoff/pgweb
        environment:
            - DATABASE_URL=postgres://codefordc:codefordc@postgres:5432/codefordc_postgres_docker?sslmode=disable
        links:
            - postgres
        ports:
            - "8081:8081"
        restart: "on-failure:10"

    postgres:
        #housing-insights-postgres is an empty Postgres 9.5 install
        image: codefordc2/housing-insights-postgres
        environment:
            - POSTGRES_PASSWORD=codefordc
            - POSTGRES_USER=codefordc
            - POSTGRES_DB=codefordc_postgres_docker
        ports:
            - "5432:5432"
        restart: "on-failure:3"

    sandbox:
        build:
            context: python
        volumes:
            - .:/repo
        command: tail -f /dev/null
        ports:
            - "5000:5000"
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=America/New_York