print("""
MMMMMMMMMMMMMMMMMMMMMMMMMMKoOWMMMMMMMMMMMMMMKx0WMMMMMMMMMMMMMMMXOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMXo.:0WMMMMMMMMMMMMNo'cKWMMMMMMMMMMMMMNd,lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWN0Okxc...;dkO0XWMWNK0Okl...:xOO0KXWMMWXXK0o'..cOKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKo,.........'c0WMWKo,..........'c0WMWKo,'........,lOWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOc.......;kNMMMMMNO:.......,lxXMMMMWXx;.......,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWx.......lXMMMMMMMWx.......l0XMMMMMMMWx.......lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXl,:dkxc,:0MMMMMMMXl';oxo:':d0MMMMMMMNl.,col;.:0MMMMMMMMMMMMW0k0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNKXWMMMWXKNMMMMMMMN0KNWMMWK00XMMMMMMMNOOXWMWN0OXMMMMMMMMMMMMO' cNMMMMMMMMMMMMM
MMMMMMMMMMWKOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo .xXOKWMMMMMMMMMM
MMMMMMMNOo;.'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; '0O'.;oONWMMMMMM
MMMWXkc'    'OMMMMMWKxddddddddddddddddddddddddddddddddddddddddddddddddddkNMMMMMMMO. cN0,    'ckKWMMM
N0d:.    ':d0WMMMMMWx...................................................;KMMMMMMWo .xMWKxc'.   .;d0N
x.   .:dONMMMMMMMMMWx...................................................;KMMMMMMK; ,KMMMMWN0d:.   .d
o    ,dKWMMMMMMMMMMWd...................................................;KMMMMMMk. lNMMMMMMWKx;.   l
Ko,.   .,lkXWMMMMMMWx...................................................:KMMMMMWl .kMMMWXOo;.   .,lK
MMN0d:.    .lKMMMMMWXkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMMMMMK, ;KMMXl.    .;d0NMM
MMMMMWXkc'  .OMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMk. oWMMO.  'cxKWMMMMM
MMMMMMMMMNOol0MMMMMWO:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oXMMMMNl .OMMMKllOXWMMMMMMMM
MMMMMMMMMMMMWWMMMMMWd...................................................;0MMMM0, ;XMMMWWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWd...................................................;KMMMMXdlOWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWx...................................................;KMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWk;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,lKMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""")